### ISSUE TITLE
error in Powerfactory 2017 SP5 x64 

### ISSUE THREAD

**Issue by FrankYinXF** [ie3-institute/simBench2PowerFactory#1]
There is an error when running in powerfactory 2017 SP5 x64.

**System:**

Powerfactory 2017 SP5 x64
Python 3.6

**Error info:**

info - SimBench to PowerFactory converter started...
err  - Traceback (most recent call last):

         File "<string>", line 27, in <module>

         File "D:\Frank\_ResearchDrive\ResearchCode_ICS\simbench-master\simBench2PowerFactory-main\simBench2PowerFactory\SimBench2PowerFactory.py", line 80, in <module>

           grid = app.GetCalcRelevantObjects("*.ElmNet",)[1] # grid objects folder

       IndexError: list index out of range

**Comment by FrankYinXF** [comment]
Sorry, no errors.
